# _config.yml
title: Dokumentasi Windows & Office
description: Panduan Upgrade Windows 11 Pro dan Instalasi Office
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      layout: default
      custom_css: /assets/css/neumorphic.css
      custom_js: /assets/js/neumorphic-tabs.js

sass:
  style: compressed

include:
  - _headers
  
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

baseurl: "/windows-docs"
url: "https://hndrapratamaa.github.io"

